//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kargo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araclar
    {
        public int AracNo { get; set; }
        public string AracTur { get; set; }
        public Nullable<int> AracKapasite { get; set; }
        public string AracSofor { get; set; }
    }
}
